version: '3.8'

services:
  app:
    build:
      target: ${BUILD_TARGET:-dev}
    image: ${APP_NAME:-parking-rue-du-moulin-front}:${IMAGE_TAG:-dev}
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - .:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-3000}"]
      interval: 1m
      timeout: 30s
      retries: 5
    networks:
      - app-network

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
      target: cypress
    image: ${APP_NAME:-parking-rue-du-moulin-front}:${IMAGE_TAG:-cypress}
    environment:
      - CYPRESS_baseUrl=http://app:${APP_PORT:-3000}
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge