# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      - ./vendor:/app/vendor
      - ./var:/app/var
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-coverage}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
  
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
    ###< doctrine/doctrine-bundle ###
  
  nextjs:
    container_name: nextjs
    build:
      context: ./pwa
      target: dev
    volumes:
      - ./pwa:/srv/app
    ports:
      - '${APP_PORT:-3000}:3000'

  cypress:
    container_name: cypress
    build:
      context: ./pwa
      dockerfile: Dockerfile
      target: cypress
    image: ${IMAGES_PREFIX:-}cypress
    environment:
      - CYPRESS_BASE_URL=http://nextjs:${APP_PORT:-3000}
    depends_on:
      - nextjs
  
  ###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
