# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
<<<<<<< HEAD
=======
      SERVER_NAME: ${SERVER_NAME:-:80}
      
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.16-alpine
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./deployment/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

>>>>>>> ec6e074 (feat: add health check endpoints, uptime-kuma)
